#profile
spring.profiles.active=online

#RocketmqClient是RocketMq中日志打印的标识
logging.level.RocketmqRemoting=error


#设置utf-8,防止中文乱码
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true


#mybatis
mybatis.mapper-locations=classpath:mapper/*.xml
#
mybatis.type-aliases-package=com.bliliblili.dao

#开启mybatis 驼峰式命名规则自动转换功能
mybatis.configuration.map-underscore-to-camel-case=true

#mybatis
logging.level.com.bliliblili.dao=debug

#Th1z4wlTJDFKe5bmFOVW2s11AYOXYo5GeO8LvPF/eL4Odn4695xb/wzdYYdD/I2xBvgEC0wPlHM1EoaXa7EWpHtk766RDaBSE1SN6WPosl005Ai3lGm1Z3PwWsnn3h0va99XaqNUTfnmiWFJ5lO1o4jozh8w0wVhKqnADyKFJ6Q=
